### PR TITLE
fxi proxy bug

### PR DESCRIPTION
**Pull request by akynazh**
for issue [#110](https://github.com/UlionTse/translators/issues/110)

### CODE REVIEW

**Comment by akynazh** [comment]
After test, In python3.10.9, there is no need to fix proxy bug, but in python3.7.9, it does. So not everyone will encounter this bug.

**Comment by UlionTse** [comment]
@akynazh Thanks, but the initial state of `requests`'s parameters `proxies` has already implemented your functionality itself. [Reference link](https://github.com/psf/requests/blob/15585909c3dd3014e4083961c8a404709450151c/requests/sessions.py#L759)

**Comment by UlionTse** [comment]
@akynazh [The function](https://docs.python.org/3.5/library/urllib.request.html#urllib.request.getproxies) you provide has been available in python3.5 at least, so it should not be a python version issue, and the issue originator notes that the version is 3.10. It is possible that the problem is with `requests`'s version in his environment. However, if the download is normal, the dependency library will be updated. So ...

**Comment by akynazh** [comment]
> @akynazh [The function](https://docs.python.org/3.5/library/urllib.request.html#urllib.request.getproxies) you provide has been available in python3.5 at least, so it should not be a python version issue, and the issue originator notes that the version is 3.10. It is possible that the problem is with `requests`'s version in his environment. However, if the download is normal, the dependency library will be updated. So ...

@UlionTse Thanks. I read the source code after your reply. It's my fault, I will close.

**Pull request closed without merging**
