### PR TITLE
:sparkle: Add CLI

### PR DESCRIPTION
**Pull request by Ousret**
I (almost) daily use this tool to quickly translate message from various foreign partner, and I built a CLI
that allows to leverage this tool directly from my terminal.

This PR add a CLI, named `translate`.

![image](https://github.com/user-attachments/assets/ff8daeea-352d-4bfe-b5cf-a30a1a03fac5)

Here is the usage:

```
> translate --help                                                                                                                                                                                                                               ─╯
usage: translate [-h] [-p PROVIDER] [-f FROM_LANGUAGE] [-t TO_LANGUAGE] [--version] input

Bring free, multiple, enjoyable translations to individuals and students.

positional arguments:
  input                 Raw text or path to a file to be translated

options:
  -h, --help            show this help message and exit
  -p PROVIDER, --provider PROVIDER
                        Choose one of the supported providers. e.g. bing, google, yandex, bing etc...
  -f FROM_LANGUAGE, --from FROM_LANGUAGE
                        Enforce the language of origin. By default it is auto detected.
  -t TO_LANGUAGE, --to TO_LANGUAGE
                        Set the destination language. Always default to english.
  --version             Show version information and exit.
```

### CODE REVIEW

**Comment by UlionTse** [comment]
Good Idea, thanks for your PR.

**Comment by Ousret** [comment]
Hello,

Any ETA for release? Would be great to be able to leverage those without passing through git install.

regards,

**Comment by UlionTse** [comment]
@Ousret 
Sorry, bro.I've been a little busy lately. 
A version update is expected in January.

**Comment by Ousret** [comment]
Thanks for the response. I understand.

**Comment by Ousret** [comment]
I saw the latest release and I was surprised.
Could you remove Niquests support altogether and issue a newer release? If you prefer Requests.

translators have 30 dependencies in the tree! It is too much.
What made you do this? You kept Requests as the default and brought httpx along the way? I am very curious on what made you do this.

Using 3 http clients is weird. Otherwise, use optional dependencies instead of mandatory one and detect which one is installed instead.

Regards.

**Comment by UlionTse** [comment]
@Ousret 
Bro, thanks for your `niquests`. 
But
I hope you will open your mind to the challenge and competition of other great libraries, and give users choices, not choose for them. The initial selection of `requests` is for service stability.

**Pull request merged**
